name: JDFLibJ Release

on:
  push:
    tags:
      - JDFLibJ-2.1.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: GPG Version
        run: gpg --version

      - name: Decrypt GPG Ring File
        env:
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: gpg --quiet --batch --yes --decrypt --passphrase="$SIGNING_PASSWORD" --output secring.gpg secring.gpg.encrypted && chmod +x secring.gpg

      - name: Import GPG Ring File
        run: gpg --batch --import secring.gpg

      - name: Maven Release Prepare
        env:
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: mvn --settings maven-settings.xml -Dgpg.passphrase=$SIGNING_PASSWORD -Dossrh.username=$OSSRH_USERNAME -Dossrh.password=$OSSRH_PASSWORD release:prepare --batch-mode -DreleaseVersion=${GITHUB_REF:8} -DdevelopmentVersion=${GITHUB_REF:8:5}.x-SNAPSHOT

      - name: Maven Release Perform
        env:
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: mvn --settings maven-settings.xml -Dgpg.passphrase=$SIGNING_PASSWORD -Dossrh.username=$OSSRH_USERNAME -Dossrh.password=$OSSRH_PASSWORD release:perform --batch-mode