name: JDFLibJ Release

on:
  push:
    tags:
      - JDFLibJ-2.1.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew build -PprojectVersion=${GITHUB_REF:18}

      - name: Attach files to GitHub Release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/libs/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts to GitHub Build Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: libs
          path: build/libs

      - name: Decrypt GGP Ring File
        env:
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: gpg --quiet --batch --yes --decrypt --passphrase="$SIGNING_PASSWORD" --output secring.gpg secring.gpg.encrypted && chmod +x secring.gpg

      - name: Debug
        run: echo $PWD/secring.gpg && ls -l

      - name: Publish artifacts to Maven Central Snapshot
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: ./gradlew publish closeAndReleaseRepository -PprojectVersion=${GITHUB_REF:18} -Psigning.keyId=$SIGNING_KEY_ID -Psigning.password=$SIGNING_PASSWORD -Psigning.secretKeyRingFile=$PWD/secring.gpg -PossrhUsername=$OSSRH_USERNAME -PossrhPassword=$OSSRH_PASSWORD
