name: Snapshot

# This build process is triggered in case changes are being pushed to the master branch.
# This process takes the latest master changes, build and test the new version and finally publish the artifacts
# to the Central Maven SNAPSHOT Repository.

on:
  push:
    branches: [ master ]

jobs:
  linux-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Trigger Bambi SNAPSHOT build
        run: |
          curl \
          -X POST \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          https://api.github.com/repos/cip4/bambi/dispatches \
          -d '{"event_type" : "trigger_bambi"}'
           
      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Artifacts to GitHub Build Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: libs
          path: build/libs

      - name: Upload Test Results to GitHub Build Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v1
        with:
          name: test-results linux
          path: build/reports/tests/test

      - name: Decrypt GGP Ring File
        env:
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: gpg --quiet --batch --yes --decrypt --passphrase="$SIGNING_PASSWORD" --output secring.gpg secring.gpg.encrypted && chmod +x secring.gpg

      - name: Debug
        run: echo $PWD/secring.gpg && ls -l

      - name: Publish artifacts to Maven Central Snapshot
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: ./gradlew publish -Psigning.keyId=$SIGNING_KEY_ID -Psigning.password=$SIGNING_PASSWORD -Psigning.secretKeyRingFile=$PWD/secring.gpg -PossrhUsername=$OSSRH_USERNAME -PossrhPassword=$OSSRH_PASSWORD

  windows-test:
    runs-on: windows-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Test with Gradle
        run: ./gradlew test

      - name: Upload Test Results to GitHub Build Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v1
        with:
          name: test-results windows
          path: build/reports/tests/test
